export const trendingSongs = [
  {
    title: "Not Like Us",
    id: "1",
    artist: "Kendrick Lamar",
    image: "/notlikeus.jpg",
  },

  {
    title: "Blinding Lights",
    artist: "The Weekend",
    id: "8",
    image: "/afterhours.jpg",
  },
  {
    title: "As It Was",
    artist: "Harry Styles",
    id: "16",
    image: "/asitwas.jpg",
  },
  {
    title: "Lover",
    artist: "Taylor Swift",
    id: "12",
    image: "/antihero.png",
  },
  {
    title: "Drivers License",
    artist: "Olivia Rodrigo",
    id: "22",
    image: "/vampire.jpg",
  },

  {
    title: "Anti-Hero",
    artist: "Taylor Swift",
    id: "11",
    image: "/antihero.png",
  },
  {
    title: "You Belong With Me",
    artist: "Taylor Swift",
    id: "14",
    image: "/antihero.png",
  },
  {
    title: "DNA.",
    artist: "Kendrick Lamar",
    id: "2",
    image: "/notlikeus.jpg",
  },
  {
    title: "Shake It Off",
    artist: "Taylor Swift",
    id: "15",
    image: "/antihero.png",
  },

  {
    title: "Golden",
    artist: "Harry Styles",
    id: "17",
    image: "/asitwas.jpg",
  },
  {
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    id: "18",
    image: "/asitwas.jpg",
  },
  {
    title: "Sign of the Times",
    artist: "Harry Styles",
    id: "19",
    image: "/asitwas.jpg",
  },
  {
    title: "Kiwi",
    artist: "Harry Styles",
    id: "20",
    image: "/asitwas.jpg",
  },
  {
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    id: "3",
    image: "/notlikeus.jpg",
  },
  {
    title: "Vampire",
    artist: "Olivia Rodrigo",
    id: "21",
    image: "/vampire.jpg",
  },
  {
    title: "Drivers License",
    artist: "Olivia Rodrigo",
    id: "22",
    image: "/vampire.jpg",
  },
  {
    title: "Good 4 U",
    artist: "Olivia Rodrigo",
    id: "23",
    image: "/vampire.jpg",
  },
  {
    title: "Deja Vu",
    artist: "Olivia Rodrigo",
    id: "24",
    image: "/vampire.jpg",
  },
  {
    title: "Brutal",
    artist: "Olivia Rodrigo",
    id: "25",
    image: "/vampire.jpg",
  },
  {
    title: "After Hours",
    artist: "The Weekend",
    id: "6",
    image: "/afterhours.jpg",
  },
  {
    title: "Save Your Tears",
    artist: "The Weekend",
    id: "7",
    image: "/afterhours.jpg",
  },
  {
    title: "Life is Good",
    artist: "Future & Drake",
    id: "26",
    image: "/drakefuture.jpg",
  },
  {
    title: "In My Feelings",
    artist: "Drake",
    id: "27",
    image: "/drake.jpg",
  },
  {
    title: "Hotline Bling",
    artist: "Drake",
    id: "28",
    image: "/drake.jpg",
  },
  {
    title: "One Dance",
    artist: "Drake",
    id: "29",
    image: "/drake.jpg",
  },
  {
    title: "Alright",
    artist: "Kendrick Lamar",
    id: "4",
    image: "/notlikeus.jpg",
  },
  {
    title: "King Kunta",
    artist: "Kendrick Lamar",
    id: "5",
    image: "/notlikeus.jpg",
  },
  {
    title: "Nonstop",
    artist: "Drake",
    id: "30",
    image: "/drake.jpg",
  },

  {
    title: "მშვიდი",
    artist: "TAHA",
    id: "31",
    image: "/calm.jpg",
  },
  {
    title: "არ მინდა",
    artist: "TAHA",
    id: "32",
    image: "/calm.jpg",
  },
  {
    title: "დიდი ქალაქი",
    artist: "TAHA",
    id: "33",
    image: "/calm.jpg",
  },
  {
    title: "ჩემი ქალაქი",
    artist: "TAHA",
    id: "34",
    image: "/calm.jpg",
  },
  {
    title: "ნაპოვნია",
    artist: "TAHA",
    id: "35",
    image: "/calm.jpg",
  },
  {
    title: "Starboy",
    artist: "The Weekend",
    id: "9",
    image: "/afterhours.jpg",
  },
  {
    title: "Can't Feel My Face",
    artist: "The Weekend",
    id: "10",
    image: "/afterhours.jpg",
  },
];

export const popularArtists = [
  {
    name: "Russ",
    role: "Artist",
    image: "/russ.jpg",
    id: "1",
  },

  {
    name: "Drake",
    role: "Artist",
    image: "/drake.jpg",
    id: "2",
  },
  {
    name: "Eminem",
    role: "Artist",
    image: "/em.jpg",
    id: "3",
  },
  {
    name: "Kanye West",
    role: "Artist",
    image: "/kanye.jpg",
    id: "4",
  },
  {
    name: "The Weekend",
    role: "Artist",
    image: "/wek.jpg",
    id: "5",
  },
  {
    name: "NF Realmusic",
    role: "Artist",
    image: "/nff.jpg",
    id: "6",
  },
  {
    name: "Ed Sheeran",
    role: "Artist",
    image: "/ed.jpg",
    id: "7",
  },
  {
    name: "Billie Eilish",
    role: "Artist",
    image: "/bilie.jpg",
    id: "8",
  },
  {
    name: "Post Malone",
    role: "Artist",
    image: "/post.jpg",
    id: "9",
  },
  {
    name: "Kendrick Lamar",
    role: "Artist",
    image: "/ken.jpg",
    id: "10",
  },
  {
    name: "Shakira",
    role: "Artist",
    image: "/shakira.jpg",
    id: "11",
  },
  {
    name: "Justin Bieber",
    role: "Artist",
    image: "/justin.jpg",
    id: "12",
  },
];
